version: '3.8'

services:
  
  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - redis-data:/data
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/
    depends_on:
      - redis
      - rabbitmq
    restart: on-failure
  
  # consumer1:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: consumer1
  #   command: python mq/consumers.py
  #   volumes:
  #     - ./app:/app/
  #   depends_on:
  #     # - rabbitmq
  #     - backend
  #   restart: always



volumes:
  redis-data: